common: &common
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: true

development:
  <<: *common
  database: enotifier_development
  username: root
  password:

test:
  <<: *common
  database: enotifier_test
  username: root
  password:

production:
  adapter: mysql2
  database: enotifier_production
  username: root
  password:
  pool: 5
