common: &common
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: true

development:
  <<: *common  
  database: enotifier_development
  username: root
  password:

test:  
  database: enotifier_test
  username: root
  password:

production:
  database: enotifier_production
  username: root
  password:  
